packages:
  - 'packages/*'
  # - 'apps/*'
  # - 'github-actions/*'
  - 'lib'

overrides:
  js-yaml: ^4.1.1
  mocha>chokidar: ^5.0.0
  mocha>diff: ^8.0.3
  mocha>serialize-javascript: ^7.0.5

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  unrs-resolver: true

engineStrict: true
